# Generated by Django 4.0.4 on 2022-04-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_app', '0003_alter_achievement_player_id_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='player_id',
            field=models.ManyToManyField(blank=True, related_name='achievements', to='trivia_app.profile'),
        ),
    ]
