# Generated by Django 4.0.4 on 2022-04-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_app', '0004_alter_achievement_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
