# Generated by Django 4.0.4 on 2022-04-21 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trivia_app', '0010_player_alter_achievement_player_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='https://images.squarespace-cdn.com/content/v1/54b7b93ce4b0a3e130d5d232/1519987020970-8IQ7F6Z61LLBCX85A65S/icon.png?format=1000w', max_length=300)),
                ('profile_text', models.TextField(blank=True, default='Tell something about yourself here...')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='player_id',
            field=models.ManyToManyField(blank=True, related_name='achievements', to='trivia_app.profile'),
        ),
        migrations.AlterField(
            model_name='result',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='trivia_app.profile'),
        ),
    ]
