# Generated by Django 4.0.4 on 2022-04-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_app', '0011_profile_delete_player_alter_achievement_player_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fact',
            field=models.TextField(blank=True, default='None'),
        ),
    ]
